apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-config
  namespace: kube-system
type: Opaque
stringData:
  config.yaml: |
    features:
      provider: default
    clusters:
      - url: https://10.10.10.1:8006/api2/json
        insecure: true
        token_id: 'nixservuser001@pam!nixservuser001'
        token_secret: 'cf0aea74-b544-40f7-9b2a-97093f4e670c'
        region: proxmox
