createNamespace: false

existingConfigSecret: proxmox-csi-config
existingConfigSecretKey: config.yaml

storageClass:
  - name: proxmox-data-xfs
    storage: lvm-4tb
    reclaimPolicy: Delete
    fstype: ext4
    cache: none
    ssd: true
    allowedTopologies:
      - matchLabelExpressions:
          - key: topology.kubernetes.io/region
            values:
              - proxmox
          - key: topology.kubernetes.io/zone
            values:
              - bhado

controller:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

node:
  nodeSelector: {}
